stages:
  - release
  - deploy

create release:
  stage: release
  image: node:10
  script:
    - npm ci
    - npm run build
    - npx semantic-release
  only:
    - master

deploy image:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG smartive/kubernetes-deploy:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG smartive/kubernetes-deploy:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push smartive/kubernetes-deploy:$CI_COMMIT_TAG
    - docker push smartive/kubernetes-deploy:latest
  only:
    - tags

deploy binaries:
  stage: deploy
  image: node:10
  before_script:
    - npm ci
  script:
    - npm run package
  artifacts:
    paths:
      - out/*
    expire_in: 1 year
  only:
    - tags
