stages:
  - test
  - release
  - deploy

.base:
  tags:
    - smartive

test:
  extends: .base
  stage: test
  image: node:10
  script:
    - npm ci
    - npm run test:ci
  coverage: /All files\s*\|\s*([\d\.]+)/
  except:
    - tags

create release:
  extends: .base
  stage: release
  image: node:10
  when: manual
  script:
    - npm ci
    - npm run build
    - npx semantic-release
  only:
    - master

deploy docker images:
  extends: .base
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_BUILDKIT: '1'
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - ./docker-build.sh
  only:
    - tags

deploy binaries:
  extends: .base
  stage: deploy
  image: node:10
  before_script:
    - npm ci
  script:
    - npm run package
  artifacts:
    paths:
      - out/*
  only:
    - tags
