stages:
  - release
  - deploy

create release:
  stage: release
  image: node:9
  script:
    - npm i -g npm
    - npm ci
    - npx semantic-release
  only:
    - master

deploy image:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://localhost:2375
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.smartive.ch
    - docker build -t registry.smartive.ch/smartive/kubernetes-deploy:$CI_COMMIT_TAG .
    - docker tag registry.smartive.ch/smartive/kubernetes-deploy:$CI_COMMIT_TAG registry.smartive.ch/smartive/kubernetes-deploy:latest
    - docker push registry.smartive.ch/smartive/kubernetes-deploy:$CI_COMMIT_TAG
    - docker push registry.smartive.ch/smartive/kubernetes-deploy:latest
  only:
    - tags

