stages:
  # - release
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

# create release:
#   stage: release
#   image: node:10
#   script:
#     - npm ci
#     - npm run build
#     - npx semantic-release
#   only:
#     - master

deploy docker images:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - ls -la
    - cat docker-build.sh
  only:
    - master

deploy binaries:
  stage: deploy
  image: node:10
  before_script:
    - npm ci
  script:
    - npm run package
  artifacts:
    paths:
      - out/*
    expire_in: 1 year
  only:
    - tags
