stages:
  - release
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

create release:
  stage: release
  image: node:10
  script:
    - npm ci
    - npm run build
    - npx semantic-release
  only:
    - master

.build-docker: &build-docker
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - docker build --build-arg KUBECTL_VERSION=$KUBECTL_VERSION -t $IMAGE:$TAG .
    - docker push $IMAGE:$TAG
  only:
    - tags

deploy local latest:
  <<: *build-docker
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: latest
    KUBECTL_VERSION: 1.11.3

deploy local tag:
  <<: *build-docker
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_TAG
    KUBECTL_VERSION: 1.11.3

deploy latest:
  <<: *build-docker
  variables:
    IMAGE: smartive/kubernetes-deploy
    TAG: latest
    KUBECTL_VERSION: 1.11.3

deploy 1.11:
  <<: *build-docker
  variables:
    IMAGE: smartive/kubernetes-deploy
    KUBECTL_VERSION: 1.11.3
    TAG: kube-1.11-k8s-$CI_COMMIT_TAG

deploy 1.10:
  <<: *build-docker
  variables:
    IMAGE: smartive/kubernetes-deploy
    KUBECTL_VERSION: 1.10.8
    TAG: kube-1.10-k8s-$CI_COMMIT_TAG

deploy 1.9:
  <<: *build-docker
  variables:
    IMAGE: smartive/kubernetes-deploy
    KUBECTL_VERSION: 1.9.10
    TAG: kube-1.9-k8s-$CI_COMMIT_TAG

deploy 1.8:
  <<: *build-docker
  variables:
    IMAGE: smartive/kubernetes-deploy
    KUBECTL_VERSION: 1.8.15
    TAG: kube-1.8-k8s-$CI_COMMIT_TAG

deploy binaries:
  stage: deploy
  image: node:10
  before_script:
    - npm ci
  script:
    - npm run package
  artifacts:
    paths:
      - out/*
    expire_in: 1 year
  only:
    - tags
