stages:
  - release
  - deploy

create release:
  stage: release
  image: node:9
  script:
    - npm i -g npm
    - npm ci
    - npm run semantic-release
  only:
    - master

deploy image:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.smartive.ch
    - docker build -t registry.smartive.ch/smartive/kubernetes-deploy:$CI_COMMIT_TAG .
    - docker push registry.smartive.ch/smartive/kubernetes-deploy:$CI_COMMIT_TAG
  only:
    - tags

